let store = {
  countries: [],
  states: [],
  cities: [],
  fillData: {
    ascendente: { signo: "", casa: "" },
    medioCielo: { signo: "", casa: "" },
    sol: { signo: "", casa: "" },
    luna: { signo: "", casa: "" },
    mercurio: { signo: "", casa: "" },
    venus: { signo: "", casa: "" },
    marte: { signo: "", casa: "" },
    jupiter: { signo: "", casa: "" },
    saturno: { signo: "", casa: "" },
    urano: { signo: "", casa: "" },
    neptuno: { signo: "", casa: "" },
    pluton: { signo: "", casa: "" },
  },
  countrie_code: "",
  countrie: "",
  countrieEs: "",
  state: "",
  city: "",
  longitud: "",
  latitud: "",
  date: "",
  timezone: "",
  time: "",
};
export default store;
